### PR TITLE
Synchronize files from linux-system-roles/template

### PR DESCRIPTION
**Pull request by systemroller**
This PR propagates files from [linux-system-roles/template](https://github.com/linux-system-roles/template) which should be in sync across [linux-system-roles](https://github.com/linux-system-roles) repos. In case of changing affected files via pushing to this PR, please do not forget also to push the changes to [linux-system-roles/template](https://github.com/linux-system-roles/template) repo.

Revision: [`8720c3e7f7f6e6ffe06679105666f08095aeb642`](https://github.com/linux-system-roles/template/tree/8720c3e7f7f6e6ffe06679105666f08095aeb642)

CC: @i386x, @pcahyna, @richm

### CODE REVIEW

**Comment by richm** [comment]
this is the result of running the sync-template.sh script - looks like it picked up a lot more than just the `molecule<3` fix - ok?

also note that almost none of the other projects have a tox.ini - @tyll fixed the one for `network` - but the other ones install `molecule` explicitly in `.travis.yml` e.g. from `storage`:
```
.travis.yml:  - pip install molecule docker
```

**Comment by richm** [comment]
@pcahyna any idea why the python 3.5 tests fail and the others pass?  It looks like many more tests run for 3.5, and are skipped for the other platforms - is it because python 3.5 is the system python?

**Comment by pcahyna** [comment]
no idea - @i386x you did most of the Travis/Tox/Python integration, could you please look at it?

**Comment by tyll** [comment]
> @pcahyna any idea why the python 3.5 tests fail and the others pass? It looks like many more tests run for 3.5, and are skipped for the other platforms - is it because python 3.5 is the system python?

Molecule needs selinux which is a binary module that is not available on PyPi, therefore it can be only used with the system Python. AFAIR, we also use the system python for static code checks that do not differ for minor python versions.

**Comment by richm** [comment]
Is it ok to merge this PR?  Or did doing the sync from the template cause these errors?

**Pull request closed without merging**
