### PR TITLE
ansible-lint 6.x fixes

### PR DESCRIPTION
**Pull request by richm**
All tasks must be named
Tasks names must begin with uppercase letter
Use `true`/`false` instead of `yes`/`no`
other changes

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest bad]

**Review by sergio-correia — APPROVED** [review]

**Pull request merged**
